In [1]:
import numpy as np
import time

In [2]:
def task_1_numpy(n):
    start_time = time.time()
    result = np.diag(np.arange(1, n + 1))
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_1_iterative(n):
    start_time = time.time()
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        result[i][i] = i + 1
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

n = 5
result_numpy, time_numpy = task_1_numpy(n)
print("NumPy result:")
print(result_numpy)
print("NumPy execution time:", time_numpy)

result_iterative, time_iterative = task_1_iterative(n)
print("\nIterative result:")
for row in result_iterative:
    print(row)
print("Iterative execution time:", time_iterative)


NumPy result:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
NumPy execution time: 4.00543212890625e-05

Iterative result:
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
Iterative execution time: 6.9141387939453125e-06


In [3]:
def task_3_numpy(n, m, r, c):
    start_time = time.time()
    result = np.ones((n, m), dtype=int)
    result[r, :] = 0
    result[:, c] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_3_iterative(n, m, r, c):
    start_time = time.time()
    result = [[1] * m for _ in range(n)]
    for i in range(n):
        result[i][c] = 0
    for j in range(m):
        result[r][j] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

n, m, r, c = 6, 7, 2, 3
result_3_numpy, time_3_numpy = task_3_numpy(n, m, r, c)
print("Task 3 - NumPy result:")
print(result_3_numpy)
print("Task 3 - NumPy execution time:", time_3_numpy)

result_3_iterative, time_3_iterative = task_3_iterative(n, m, r, c)
print("\nTask 3 - Iterative result:")
for row in result_3_iterative:
    print(row)
print("Task 3 - Iterative execution time:", time_3_iterative)


Task 3 - NumPy result:
[[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]]
Task 3 - NumPy execution time: 0.00011086463928222656

Task 3 - Iterative result:
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
Task 3 - Iterative execution time: 1.0013580322265625e-05


In [5]:
def task_4_numpy(n, m):
    start_time = time.time()
    result = np.zeros((n, m), dtype=int)
    result[0, :] = np.arange(m)
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_4_iterative(n, m):
    start_time = time.time()
    result = [[0] * m for _ in range(n)]
    for j in range(m):
        result[0][j] = j
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

n, m = 3, 4
result_4_numpy, time_4_numpy = task_4_numpy(n, m)
print("\nTask 4 - NumPy result:")
print(result_4_numpy)
print("Task 4 - NumPy execution time:", time_4_numpy)

result_4_iterative, time_4_iterative = task_4_iterative(n, m)
print("\nTask 4 - Iterative result:")
for row in result_4_iterative:
    print(row)
print("Task 4 - Iterative execution time:", time_4_iterative)



Task 4 - NumPy result:
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Task 4 - NumPy execution time: 7.295608520507812e-05

Task 4 - Iterative result:
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
Task 4 - Iterative execution time: 7.867813110351562e-06


In [11]:
def task_6_numpy(arr):
    arr_np = np.array(arr)
    arr_np[arr_np != 0] = -1
    return arr_np

def task_6_iterative(arr):
    result = []
    for num in arr:
        if num != 0:
            result.append(-1)
        else:
            result.append(0)
    return result

input_array = [3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]

result_numpy = task_6_numpy(input_array)
print("NumPy result:", result_numpy)

result_iterative = task_6_iterative(input_array)
print("Iterative result:", result_iterative)


NumPy result: [-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Iterative result: [-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]


In [6]:
def task_10(n, m):
    # Створення масиву випадкових значень n×m
    random_array = np.random.rand(n, m)
    
    # Обчислення мінімального, максимального значення та середнього
    min_value = np.min(random_array)
    max_value = np.max(random_array)
    mean_value = np.mean(random_array)
    
    # Обчислення дисперсії (середньо квадратичне відхилення)
    variance = np.var(random_array)
    std_deviation = np.sqrt(variance)
    
    return min_value, max_value, mean_value, round(std_deviation, 3)

n, m = 4, 5
min_val, max_val, mean_val, std_dev = task_10(n, m)

print("мінімум:", min_val)
print("максимум:", max_val)
print("середнє:", mean_val)
print("дисперсія:", std_dev)


мінімум: 0.1337744579469028
максимум: 0.9869246832480808
середнє: 0.6433995687546378
дисперсія: 0.268


In [7]:
def task_12_numpy(n):
    start_time = time.time()
    result = np.ones((n, n))
    result[1:-1, 1:-1] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_12_iterative(n):
    start_time = time.time()
    result = []
    result.append([0] * n)
    for _ in range(n - 2):
        row = [0] + [1] * (n - 2) + [0]
        result.append(row)
    result.append([0] * n)
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

n = 4

result_numpy, time_numpy = task_12_numpy(n)
print("NumPy result:")
print(result_numpy)
print("NumPy execution time:", time_numpy)

result_iterative, time_iterative = task_12_iterative(n)
print("\nIterative result:")
for row in result_iterative:
    print(row)
print("Iterative execution time:", time_iterative)


NumPy result:
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
NumPy execution time: 6.914138793945312e-05

Iterative result:
[0, 0, 0, 0]
[0, 1, 1, 0]
[0, 1, 1, 0]
[0, 0, 0, 0]
Iterative execution time: 7.152557373046875e-06


In [8]:
def task_15_numpy(n):
    start_time = time.time()
    result = np.zeros((n, n), dtype=int)
    result[:, ::2] = 1
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_15_iterative(n):
    start_time = time.time()
    result = []
    for i in range(n):
        row = [1 if i % 2 == 0 else 0 for i in range(n)]
        result.append(row)
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

n = 5

result_numpy, time_numpy = task_15_numpy(n)
print("NumPy result:")
print(result_numpy)
print("NumPy execution time:", time_numpy)

result_iterative, time_iterative = task_15_iterative(n)
print("\nIterative result:")
for row in result_iterative:
    print(row)
print("Iterative execution time:", time_iterative)


NumPy result:
[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]
NumPy execution time: 5.2928924560546875e-05

Iterative result:
[1, 0, 1, 0, 1]
[1, 0, 1, 0, 1]
[1, 0, 1, 0, 1]
[1, 0, 1, 0, 1]
[1, 0, 1, 0, 1]
Iterative execution time: 8.821487426757812e-06


In [10]:
def task_17_numpy(n):
    start_time = time.time()
    vector = np.arange(n)
    vector[(vector < n/2) | (vector > 3*n/4)] *= -1
    end_time = time.time()
    execution_time = end_time - start_time
    return vector, execution_time

def task_17_iterative(n):
    start_time = time.time()
    vector = list(range(n))
    for i in range(len(vector)):
        if vector[i] < n/2 or vector[i] > 3*n/4:
            vector[i] *= -1
    end_time = time.time()
    execution_time = end_time - start_time
    return vector, execution_time

n = 10
result_17_numpy, time_17_numpy = task_17_numpy(n)
print("Task 17 - NumPy result:")
print(result_17_numpy)
print("Task 17 - NumPy execution time:", time_17_numpy)

result_17_iterative, time_17_iterative = task_17_iterative(n)
print("\nTask 17 - Iterative result:")
print(result_17_iterative)
print("Task 17 - Iterative execution time:", time_17_iterative)


Task 17 - NumPy result:
[ 0 -1 -2 -3 -4  5  6  7 -8 -9]
Task 17 - NumPy execution time: 0.0002429485321044922

Task 17 - Iterative result:
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9]
Task 17 - Iterative execution time: 1.71661376953125e-05


In [11]:

def task_18_numpy(n):
    start_time = time.time()
    vector = np.random.randint(0, 100, size=n)
    unique_count = len(np.unique(vector))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

def task_18_iterative(n):
    start_time = time.time()
    vector = [np.random.randint(0, 100) for _ in range(n)]
    unique_count = len(set(vector))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

n = 30
result_18_numpy, time_18_numpy = task_18_numpy(n)
print("\nTask 18 - NumPy result:")
print("Унікальних чисел:", result_18_numpy)
print("Task 18 - NumPy execution time:", time_18_numpy)

result_18_iterative, time_18_iterative = task_18_iterative(n)
print("\nTask 18 - Iterative result:")
print("Унікальних чисел:", result_18_iterative)
print("Task 18 - Iterative execution time:", time_18_iterative)




Task 18 - NumPy result:
Унікальних чисел: 26
Task 18 - NumPy execution time: 0.0004239082336425781

Task 18 - Iterative result:
Унікальних чисел: 27
Task 18 - Iterative execution time: 0.00017786026000976562


In [34]:
import numpy as np

# Визначення матриці коефіцієнтів та вектора правих частин
A = np.array([[1, 5, 3, -4],
              [3, 1, -2, 0],
              [5, -7, 0, 10],
              [0, 3, -5, 0]])

b = np.array([20, 9, -9, 1])

# Розрахунок визначника матриці коефіцієнтів
det_A = np.linalg.det(A)

# Якщо визначник матриці коефіцієнтів рівний нулю, то система рівнянь не має єдиного розв'язку
if det_A == 0:
    print("Система рівнянь не має єдиного розв'язку, оскільки визначник матриці коефіцієнтів дорівнює нулю.")
else:
    # Розрахунок значень невідомих за формулами Крамера
    x = np.zeros(len(b))
    for i in range(len(b)):
        A_temp = A.copy()
        A_temp[:, i] = b
        x[i] = np.linalg.det(A_temp) / det_A

    print("За формулами Крамера:")
    print("x =", x)

    # Перевірка розв'язку за допомогою матричного множення
    print("\nПеревірка за допомогою матричного множення:")
    verification_mult = A @ x
    print("A @ x =", verification_mult)

    # Перевірка розв'язку за допомогою оберненої матриці
    print("\nПеревірка за допомогою оберненої матриці:")
    A_inv = np.linalg.inv(A)
    verification_inv = A_inv @ b
    print("A_inv @ b =", verification_inv)

    # Перевірка розв'язку за допомогою функції numpy.linalg.solve()
    print("\nПеревірка за допомогою функції numpy.linalg.solve():")
    x_solve = np.linalg.solve(A, b)
    print("x_solve =", x_solve)

    # Порівняння всіх рішень за допомогою функції numpy.allclose()
    result_allclose_kramer = np.allclose(A @ x, b)
    result_allclose_mult = np.allclose(A @ x, b)
    result_allclose_inv = np.allclose(A_inv @ b, b)
    result_allclose_solve = np.allclose(x_solve, x)

    # Виведення результатів порівнянь
    print("\nРезультат порівняння за формулами Крамера:", result_allclose_kramer)
    print("Результат порівняння за допомогою матричного множення:", result_allclose_mult)
    print("Результат порівняння за допомогою оберненої матриці:", result_allclose_inv)
    print("Результат порівняння за допомогою функції numpy.linalg.solve():", result_allclose_solve)


За формулами Крамера:
x = [ 3.  2.  1. -1.]

Перевірка за допомогою матричного множення:
A @ x = [20.  9. -9.  1.]

Перевірка за допомогою оберненої матриці:
A_inv @ b = [ 3.  2.  1. -1.]

Перевірка за допомогою функції numpy.linalg.solve():
x_solve = [ 3.  2.  1. -1.]

Результат порівняння за формулами Крамера: True
Результат порівняння за допомогою матричного множення: True
Результат порівняння за допомогою оберненої матриці: False
Результат порівняння за допомогою функції numpy.linalg.solve(): True


In [12]:
import numpy as np

def iterative_method(A, B):
  C = np.zeros_like(A)
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      a_minus_b_square = A[i, j] - B[i, j]**2
      two_a_plus_b = 2*A[i, j] + B[i, j]
      C[i, j] = a_minus_b_square * two_a_plus_b
  return C

def numpy_method(A, B):
  a_minus_b_square = A - B**2
  two_a_plus_b = 2*A + B
  return a_minus_b_square * two_a_plus_b

A = np.array([[5, 2, 0],
               [10, 4, 1],
               [7, 3, 2]])

B = np.array([[3, 6, -1],
               [-1, -2, 0],
               [2, 1, 3]])

C_iterative = iterative_method(A, B)
C_numpy = numpy_method(A, B)

print("Ітеративний метод:")
print(C_iterative)

print("Метод Numpy:")
print(C_numpy)

print("Порівняння результатів:")
print(np.allclose(C_iterative, C_numpy))


Ітеративний метод:
[[ -52 -340    1]
 [ 171    0    2]
 [  48   14  -49]]
Метод Numpy:
[[ -52 -340    1]
 [ 171    0    2]
 [  48   14  -49]]
Порівняння результатів:
True
